// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRyS6x8kZjUxNNnidRPpC2QtUDssf090',
    appId: '1:1059581820176:web:3e9aaf8122135ae96af995',
    messagingSenderId: '1059581820176',
    projectId: 'caddy-log-92809',
    authDomain: 'caddy-log-92809.firebaseapp.com',
    storageBucket: 'caddy-log-92809.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojxYWsLXBKS2-ayoyc2tCJcKyEvF26vY',
    appId: '1:1059581820176:android:a752a261563641cf6af995',
    messagingSenderId: '1059581820176',
    projectId: 'caddy-log-92809',
    storageBucket: 'caddy-log-92809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3yktunazkW7nD_N5gYFn3rQWLs7WuDmE',
    appId: '1:1059581820176:ios:f4d772ea8e4b97a66af995',
    messagingSenderId: '1059581820176',
    projectId: 'caddy-log-92809',
    storageBucket: 'caddy-log-92809.firebasestorage.app',
    iosBundleId: 'com.andreaperdoncin.caddylog2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3yktunazkW7nD_N5gYFn3rQWLs7WuDmE',
    appId: '1:1059581820176:ios:f4d772ea8e4b97a66af995',
    messagingSenderId: '1059581820176',
    projectId: 'caddy-log-92809',
    storageBucket: 'caddy-log-92809.firebasestorage.app',
    iosBundleId: 'com.andreaperdoncin.caddylog2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvRyS6x8kZjUxNNnidRPpC2QtUDssf090',
    appId: '1:1059581820176:web:71c6f17273163ca46af995',
    messagingSenderId: '1059581820176',
    projectId: 'caddy-log-92809',
    authDomain: 'caddy-log-92809.firebaseapp.com',
    storageBucket: 'caddy-log-92809.firebasestorage.app',
  );
}
